version: "3.8"

services:
  vizonapi:
    image: satayking/vizonapi:0.0.2
    container_name: vizonapi
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - vizonapi-internal
      - reverseproxy-nw

  redis:
    image: redis:alpine
    container_name: redis-vizonapi
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - vizonapi-internal

volumes:
  redis_data:

networks:
  vizonapi-internal:
  reverseproxy-nw:
    external: true
